VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CJobCreater"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function CreatObject(objectName As String) As IJob
'    If objectName = "JobGetVIN" Then Set CreatObject = New CJobGetVIN
'    If objectName = "object2" Then Set CreatObject = New CObject2
'    If objectName = "object3" Then Set CreatObject = New CObject3
'    If objectName = "object3" Then Set CreatObject = New CObject3
'    If objectName = "object3" Then Set CreatObject = New CObject3
'    If objectName = "object3" Then Set CreatObject = New CObject3
'    If objectName = "object3" Then Set CreatObject = New CObject3
'    If objectName = "object3" Then Set CreatObject = New CObject3
'    If objectName = "object3" Then Set CreatObject = New CObject3
'    If objectName = "object3" Then Set CreatObject = New CObject3
'    If objectName = "object3" Then Set CreatObject = New CObject3
'    If objectName = "object3" Then Set CreatObject = New CObject3
End Function
